// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htpwdshscemhnadbapub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0cHdkc2hzY2VtaG5hZGJhcHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDg4NDgsImV4cCI6MjA2NzA4NDg0OH0.iir8R14Lc-HSpND9cotCZSotTu3fz1gHq6tRe7q3kb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});